name: mihox
description: Fork multi-platform proxy client FlClashX based on Mihomo, simple and easy to use, open-source and ad-free.
publish_to: "none"
version: 0.5.0+2026071015

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  animations: ^2.2.0
  app_links: ^7.2.1
  archive: ^4.0.9
  collection: ^1.19.1
  dio: ^5.10.0
  dynamic_color: ^1.8.1
  ffi: ^2.2.0
  file_picker: ^12.0.0-beta.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  json_annotation: ^4.9.0
  mobile_scanner: ^7.2.1
  path: ^1.9.1
  path_provider: ^2.1.6
  proxy:
    path: plugins/proxy
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.5
  win32: ^6.3.0
  win32_registry: ^3.0.3
  window_ext:
    path: plugins/window_ext
  window_manager: ^0.5.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  http: ^1.6.0
  nativeapi: ^0.1.1
  network_info_plus: ^8.0.0
  package_info_plus: ^10.0.0
  freezed_annotation: ^2.4.4
  image_picker: ^1.2.1
  re_editor: ^0.10.0
  re_highlight: ^0.0.3
  lpinyin: ^2.0.3
  emoji_regex: ^0.0.5
  hotkey_manager: ^0.2.3
  uni_platform: ^0.1.3
  device_info_plus: ^13.2.0
  connectivity_plus: ^7.3.0
  defer_pointer: ^0.0.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_js: ^0.8.7
  flutter_svg: ^2.3.0
  flutter_cache_manager: ^3.4.1
  cached_network_image: ^3.4.1
  crypto: ^3.0.7
  riverpod: ^2.6.1
  material_color_utilities: ^0.13.0

dev_dependencies:
  args: ^2.7.0
  build_runner: ^2.5.4
  custom_lint: ^0.7.3
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  json_serializable: ^6.9.5
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/fonts/
    - assets/images/
    - assets/images/avatars/
    - assets/images/icons/
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
    - family: Twemoji
      fonts:
        - asset: assets/fonts/Twemoji.Mozilla.ttf
    - family: Icons
      fonts:
        - asset: assets/fonts/Icons.ttf
    - family: Unbounded
      fonts:
        - asset: assets/fonts/Unbounded-Regular.ttf

ffigen:
  name: "MihomoFFI"
  output: "lib/mihomo/generated/mihomo_ffi.dart"
  headers:
    entry-points:
      - "libmihomo/android/arm64-v8a/libmihomo.h"

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  arb_dir: arb
  output_dir: lib/l10n

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#202020"
  adaptive_icon_foreground: "assets/images/icon.png"
  adaptive_icon_monochrome: "assets/images/icon_white.png"
