display_name: MihoX

packager: remtrik
packagerEmail: remtrik@mail.ru
license: Other

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

keywords:
  - MihoX
  - Mihomo
  - Proxy

generic_name: MihoX

group: Applications/Internet

startup_notify: true