display_name: MihoX
package_name: MihoX
maintainer:
  name: remtrik
  email: remtrik@mail.ru

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator3-dev
  - libkeybinder-3.0-dev

keywords:
  - MihoX
  - Mihomo
  - MihomoMeta
  - Proxy

generic_name: MihoX

categories:
  - Network

startup_notify: true