script_template: inno_setup.iss
app_id: 728B3532-C74B-4870-9068-BE70FE12A3E6
app_name: MihoX
publisher: remtrik
publisher_url: https://github.com/remtrik/MihoX
display_name: MihoX
create_desktop_icon: true
executable_name: MihoX.exe
output_base_file_name: MihoX.exe
setup_icon_file: windows\runner\resources\app_icon.ico
privileges_required: admin